
name: Escaneo de fugas con Gitleaks
on:
  push:

jobs:
  scan:
    name: Análisis de fugas con Gitleaks
    runs-on: ubuntu-latest

    steps:

      - name: Clonación del repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ejecución de Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
